### ISSUE TITLE
Error: Cannot find module 'thrift/transport'

### ISSUE THREAD

**Issue by peking2** [forward/node-hive#3]
Hello

I'm encountering this problem. At the beginning, it complained thrift was missing. Once I installed thrift, it complains that thrift/transport is missing. What modules should I install to resolve it?

at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/gzhao/test/node_modules/node-hive/node-hive.js:2:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/packages/installed/display_activity_processor-HEAD/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/gzhao/test/test.coffee:1:8, <js>:4:10)
  at Object.<anonymous> (/home/gzhao/test/test.coffee:1:1, <js>:14:4)
  at Module._compile (module.js:456:26)

Thanks.

**Comment by doxav** [comment]
I assume you followed the tutorial. You don't need to require thrift transport. The code below worked for me:
var thrift = require('thrift');
transport = thrift.TBufferedTransport();
protocol = thrift.TBinaryProtocol();

**Comment by typeofgraphic** [comment]
I am also having the same issue - 'Error: Cannot find module 'thrift/transport'

**Comment by doxav** [comment]
As I suggested previously, have you tried "not to require thrift/transport" but to use this code instead:
var thrift = require('thrift');
transport = thrift.TBufferedTransport();
protocol = thrift.TBinaryProtocol();

**Comment by typeofgraphic** [comment]
I was never trying to include thrift/transport, or thrift at first - only node-hive. I want to query some data on Hive (someone else set this up, clearly I am new to Hive here).

After running npm install node-hive the console throws an error that thrift is missing... npm install thrift..  - 'Error: Cannot find module 'thrift/transport'

To answer your question, yes I used the above code and it didn't solve my issue. I am putting the code in the var .. require(stuff) section of app.js.

**Comment by doxav** [comment]
I just remember that I first confused between npm install node-thrift and
npm install thrift, then I had to change includes in my code as per the
code suggested before. No clue if Hive may have the same kind of problem.

**Comment by lethalbrains** [comment]
:+1:  @doxav

**Comment by nikhil32** [comment]
Hi @doxav , I tried and getting same issue require  thrift/transport. 
Is there any update for this issue. If so please let me know.

**Comment by seanwendt** [comment]
+1

**Comment by vardancse** [comment]
Any update guys?

**Comment by daumann** [comment]
Put your thrift dependency to 0.9.1, that should fix the issue.

**Comment by cmorrow** [comment]
@daumann changing the Thrift dependency to "0.9.1" does not fix the problem for me.

**Comment by daumann** [comment]
@cmorrow indeed that was the issue for the repo **node-thrift-hive**, in which the [example](https://github.com/wdavidw/node-thrift-hive/blob/master/samples/style_native.js) requires transport at "thrift/lib/thrift/transport" but has the dependency of Thrift on latest. There depending on 0.9.1 fixes the issue there.

In this case, notice that the package.json does not have any dependencies but the node_modules are "hardcoded". So when running node-hive.js it depends on this specific folder structure inside node_modules. If you use a global Thrift installation it will fail, as well as if you add thrift to the dependencies and do npm install - because the folder structure is different.

**Comment by AjeetSahu** [comment]
I am using thrift-hive. i am getting following error

Cannot find module 'thrift/lib/thrift/transport'

Error: Cannot find module 'thrift/lib/thrift/transport'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/hduser/rproj/testproj1/node_modules/thrift-hive/lib/hive.js:12:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
I have tried changing the Thrift dependency to "0.9.1" and added
var thrift = require('thrift');
transport = thrift.TBufferedTransport();
protocol = thrift.TBinaryProtocol();
to hive.js but these did not work for me. Please help.

**Comment by daumann** [comment]
@AjeetSahu 
- leave hive.js as it is
- change thrift dependency in package.json to "thrift": "0.9.1"
- (if you did execute npm install before, remove node_modules folder)
- npm install

or if you like to keep Thrift on latest:
- replace https://github.com/wdavidw/node-thrift-hive/blob/master/lib/hive.js#L11 with transport = require('thrift/lib/nodejs/lib/thrift/transport');

**Comment by AjeetSahu** [comment]
Hi Daumann
Thanks for your help. I have got rid of that error....But now i am getting following error

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:10000
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1077:14)

npm ERR! Linux 3.19.0-64-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! testproj1@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 

Could you please guide me how to resolve this error.

**Comment by ruchit31** [comment]
hive commands are not working  (even console.log() is not working)

var client = hive.createClient({
  version: '0.7.1-cdh3u2',
  server: '127.0.0.1',
  port: 10000,
  timeout: 1000
});
// Execute call 
client.execute('use default', function(err){
  // Query call 
    console.log("ruchill");
  client.query('show tables')
  .on('row', function(database){
    console.log(database+"ruchi");
  })
  .on('error', function(err){
    console.log(err.message);
    client.end();
  })
  .on('end', function(){
    client.end();
  });
});

**Comment by ruchit31** [comment]
@daumann 
//hive query and console.log is not working 
var client = hive.createClient({
  version: '0.7.1-cdh3u2',
  server: '127.0.0.1',
  port: 10000,
  timeout: 1000
});
// Execute call 
client.execute('use default', function(err){
  // Query call 
    console.log("ruchill");
  client.query('show tables')
  .on('row', function(database){
    console.log(database+"ruchi");
  })
  .on('error', function(err){
    console.log(err.message);
    client.end();
  })
  .on('end', function(){
    client.end();
  });
});

**Comment by ruchit31** [comment]
Hi @daumann  Thanks for making this node module and making it available to us, can you please look into this error, I am stuck in this from past 2 days . Thank you so much :)

**Comment by hardikphp** [comment]
Please follow two step to fix the issue in Node.js
As per @doxav  given code, put that code on **thrift-hive/lib/hive.js**

`transport = require('thrift/lib/thrift/transport');`

Replace code with

```
thrift = require('thrift');
transport = thrift.TBufferedTransport();
protocol = thrift.TBinaryProtocol();


```

**Comment by Leo555** [comment]
I changed "transport = thrift.TBufferedTransport()", but got "Cannot read property 'TBufferedTransport' of undefined"

**Comment by hardikphp** [comment]
@Leo555  yes, it will not work as new version hive does not support it, try [http://stackoverflow.com/questions/38670740/error-in-connecting-node-js-application-to-hive/39529926#39529926](url)
